### ISSUE TITLE
Breaking change in v3.4.0 for nrlambda v1.0.0

### ISSUE THREAD

**Issue by rittneje** [newrelic/go-agent#140]
When upgrading github.com/newrelic/go-agent/v3 from v3.3.0 to v3.4.0, we encountered a build failure:
```
github.com/newrelic/go-agent/v3/integrations/nrlambda/handler.go:48:45: undefined: internal.AttributeAWSLambdaEventSourceARN
```

This issue is fixed by also upgrading github.com/newrelic/go-agent/v3/integrations/nrlambda from v1.0.0 to v1.1.0. However, this was not mentioned in the release notes.
https://github.com/newrelic/go-agent/releases/tag/v3.4.0
https://docs.newrelic.com/docs/release-notes/agent-release-notes/go-release-notes/go-agent-340

**Comment by newrelic-eheinlein** [comment]
@rittneje Thank you for letting us know about this! We apologize for missing this in our release notes. We’ve added a step to our release process to make sure that we don’t miss this again, and we will be updating the release notes and documents for the 3.4.0 release to make this clear.

Again, thank you for bringing this to our attention and apologies for the inconvenience.

**Comment by newrelic-eheinlein** [comment]
We have updated the [Changelog](https://github.com/newrelic/go-agent/blob/master/CHANGELOG.md#changes) to note this detail. Thank you again for catching this and reporting it.
